policy_name: EchoPolicy
protocol: ws
host: 127.0.0.1
port: 17001
bench_name: RoboDojo
task_name: cover_blocks
env_cfg_type: arx_x5
seed: 0
eval_batch: true
action_type: joint
train_config_name: pi05_base_aloha_full_sim_arx-x5_seed_0
repo_id: arx_x5_sim
checkpoint_num: 59999
checkpoint_path: null
ckpt_name: null
gpu_id: null
batch_size: 160
warmup: true
