_wandb:
    value:
        cli_version: 0.26.1
        e:
            u3cpnile4ubwx9m4v8zw29ce0t7oc3hp:
                args:
                    - --data_root
                    - /mnt/xspark-data/xspark_shared/spirit_datasets/robodojo_cotrain
                    - --pretrained_path
                    - /mnt/xspark-data/xspark_shared/model_weights/Spirit-v1.5
                    - --output_dir
                    - /mnt/nfs/niantian/RoboDojo_env/XPolicyLab/policy/Spirit_v15/checkpoints/RoboDojo-cotrain-arx_x5-100-ee-0
                    - --batch_size
                    - "32"
                    - --max_train_steps
                    - "50000"
                    - --log_interval
                    - "25"
                    - --save_steps
                    - "2500"
                    - --num_workers
                    - "4"
                    - --prefetch_factor
                    - "8"
                    - --wandb_mode
                    - online
                    - --seed
                    - "0"
                codePath: policy/Spirit_v15/spirit_v15/train.py
                codePathLocal: train.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "528147169280"
                        used: "46010159104"
                email: 1250576969@qq.com
                executable: /mnt/nfs/niantian/RoboDojo_env/XPolicyLab/policy/Spirit_v15/spirit_v15/.venv/bin/python
                git:
                    commit: 002b64a0b4e3e2f73202d2268fc87a18ad3697e7
                    remote: https://github.com/Luminis-Sim/XPolicyLab.git
                gpu: NVIDIA A800-SXM4-80GB
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-d60715fd-9a04-25a5-d20e-82f405a4529b
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-3da5bb7f-c4d7-521a-4b3d-f1e33fcdeba0
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-dad2dd42-9d01-6d64-25a3-cd007448c3df
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-ed9b3ac7-0593-a948-e9ac-1b2818395c47
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-75ab68bb-f250-7a37-98bd-125c7c7d370a
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-3b602ae6-da1b-87c1-3d37-8dc7b804a54d
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-2ff5fee8-2773-b550-8cd4-3e90436cc4b2
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A800-SXM4-80GB
                      uuid: GPU-69b641d0-ba0d-8023-1786-62f0fcf4a866
                host: instance-izb8k1bh-1
                memory:
                    total: "1079939956736"
                os: Linux-5.15.0-72-generic-x86_64-with-glibc2.35
                program: /mnt/nfs/niantian/RoboDojo_env/XPolicyLab/policy/Spirit_v15/spirit_v15/train.py
                python: CPython 3.13.13
                root: /mnt/nfs/niantian/RoboDojo_env/XPolicyLab/policy/Spirit_v15/spirit_v15
                startedAt: "2026-06-02T08:32:54.838167Z"
                writerId: u3cpnile4ubwx9m4v8zw29ce0t7oc3hp
        m: []
        python_version: 3.13.13
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "3":
                - 16
            "4": 3.13.13
            "5": 0.26.1
            "6": 4.57.1
            "12": 0.26.1
            "13": linux-x86_64
wandb_mode:
    value: online
wandb_project:
    value: spirit-v1.5
