#!/usr/bin/env python
"""Derive 80-d profiles and statistics from converted 75-d mobile profiles.

Run after convert_mobile.py. Parquet state/actions are remapped; videos are
linked from the source profiles."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from mmabc.embodiments import mobile  # noqa: E402
from mmabc.paths import home_path, relative_to_home  # noqa: E402

DEFAULT_SRC = home_path("data/mobile_mmabc")
DEFAULT_OUT = home_path("data/mobile_mmabc_c80")


def _fixed(arr: np.ndarray):
    import pyarrow as pa

    arr = np.ascontiguousarray(arr, dtype=np.float32)
    return pa.FixedSizeListArray.from_arrays(pa.array(arr.reshape(-1)), arr.shape[1])


def convert_parquet(src: Path, dst: Path) -> bool:
    import pyarrow.parquet as pq

    if dst.exists() and dst.stat().st_mtime >= src.stat().st_mtime:
        return False
    table = pq.read_table(src)
    cols = {}
    for name in table.column_names:
        if name in ("observation.state", "action"):
            flat = table.column(name).combine_chunks().flatten().to_numpy()
            cols[name] = _fixed(mobile.to_c80(flat.reshape(len(table), -1)))
        else:
            cols[name] = table.column(name)
    import pyarrow as pa

    dst.parent.mkdir(parents=True, exist_ok=True)
    tmp = dst.with_suffix(".parquet.tmp")
    pq.write_table(pa.table(cols), tmp, row_group_size=256)
    os.replace(tmp, dst)
    return True


def build_profile(src: Path, dst: Path) -> int:
    changed = 0
    for pq_file in sorted((src / "data").rglob("*.parquet")):
        changed += convert_parquet(pq_file, dst / pq_file.relative_to(src))
    videos = dst / "videos"
    if videos.is_symlink() or videos.exists():
        videos.unlink()
    # Relative, so the data tree can be moved as a whole.
    videos.symlink_to(os.path.relpath(src / "videos", dst), target_is_directory=True)

    meta_src, meta_dst = src / "meta", dst / "meta"
    meta_dst.mkdir(parents=True, exist_ok=True)
    for name in ("tasks.parquet", "modality.json"):
        shutil.copy(meta_src / name, meta_dst / name)
    shutil.copytree(meta_src / "episodes", meta_dst / "episodes", dirs_exist_ok=True)

    info = json.loads((meta_src / "info.json").read_text())
    info["features"]["observation.state"]["shape"] = [mobile.C80_DIM]
    info["features"]["action"]["shape"] = [mobile.C80_DIM]
    info["layout"] = mobile.contract("c80")
    (meta_dst / "info.json").write_text(json.dumps(info, indent=1))
    (meta_dst / "embodiment.json").write_text(json.dumps({
        "embodiment_tag": mobile.C80_TAG,
        "robot_type": mobile.ROBOT_TYPE,
        "record_frequency": mobile.FPS,
        "canonical": {
            "embodiment_tag": mobile.C80_TAG,
            "total_dim": mobile.C80_DIM,
            "action_valid_dims": mobile.C80_VALID,
            "state_valid_dims": mobile.C80_VALID,
        },
    }, indent=1))
    return changed


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", type=Path, default=DEFAULT_SRC)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--samples-per-profile", type=int, default=20000)
    ap.add_argument("--workers", type=int, default=8)
    args = ap.parse_args()

    tasks = sorted(p.name for p in args.src.iterdir() if (p / "meta" / "info.json").exists())
    for task in tasks:
        n = build_profile(args.src / task, args.out / task)
        print(f"{task:32s} {n} parquet files rewritten", flush=True)

    # Profiles and mixture mirror the 75-d ones (same views, same task weights).
    emb_dir = REPO / "configs" / "embodiments"
    lines = [
        "# Generated by scripts/build_mobile_c80.py: Mobile in the 80-d pretrain layout.",
        "canonical: configs/canonical/canonical_80_mobile.yaml",
        "datasets:",
    ]
    base_mix = (REPO / "configs" / "mixture" / "mobile_all.yaml").read_text()
    for task in tasks:
        src_cfg = (emb_dir / f"mobile_{task}.yaml").read_text()
        cfg = (src_cfg.replace(f"name: mobile_{task}", f"name: mobile_c80_{task}")
               .replace(relative_to_home(args.src / task), relative_to_home(args.out / task))
               .replace(f"embodiment_tag: {mobile.EMBODIMENT_TAG}", f"embodiment_tag: {mobile.C80_TAG}"))
        (emb_dir / f"mobile_c80_{task}.yaml").write_text(cfg)
        weight = next(l.split("weight:")[1].strip(" }") for l in base_mix.splitlines() if f"mobile_{task}.yaml" in l)
        lines.append(f"  - {{config: configs/embodiments/mobile_c80_{task}.yaml, weight: {weight}}}")
    mixture = REPO / "configs" / "mixture" / "mobile_c80_all.yaml"
    mixture.write_text("\n".join(lines) + "\n")
    print(f"wrote {mixture}")

    cmd = [sys.executable, str(REPO / "scripts" / "compute_norm_stats.py"),
           "--mixture", str(mixture.relative_to(REPO)), "--chunk-size", "32",
           "--samples-per-profile", str(args.samples_per_profile), "--workers", str(args.workers)]
    print(" ".join(cmd), flush=True)
    return subprocess.call(cmd, cwd=str(REPO))


if __name__ == "__main__":
    raise SystemExit(main())
